version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: root
      MYSQL_PASSWORD: Kanujan@123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "5009:5009"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: Kanujan@123
      DB_NAME: todo
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data: